// Mocks generated by Mockito 5.4.6 from annotations
// in kinder/test/cubit_tests/liked_cats_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kinder/data/datasources/local_database.dart' as _i5;
import 'package:kinder/data/liked_cats_repository.dart' as _i2;
import 'package:kinder/domain/models/liked_cat.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LikedCatsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLikedCatsRepository extends _i1.Mock
    implements _i2.LikedCatsRepository {
  MockLikedCatsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.LikedCat>> getLikedCats() =>
      (super.noSuchMethod(
            Invocation.method(#getLikedCats, []),
            returnValue: _i3.Future<List<_i4.LikedCat>>.value(<_i4.LikedCat>[]),
          )
          as _i3.Future<List<_i4.LikedCat>>);

  @override
  _i3.Future<void> addLikedCat(_i4.LikedCat? cat) =>
      (super.noSuchMethod(
            Invocation.method(#addLikedCat, [cat]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeLikedCat(String? catId) =>
      (super.noSuchMethod(
            Invocation.method(#removeLikedCat, [catId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addDislikedCat(_i4.LikedCat? cat) =>
      (super.noSuchMethod(
            Invocation.method(#addDislikedCat, [cat]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Cat>> getAllCats() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCats, []),
            returnValue: _i3.Future<List<_i5.Cat>>.value(<_i5.Cat>[]),
          )
          as _i3.Future<List<_i5.Cat>>);

  @override
  _i3.Future<void> upsertCat(_i5.Cat? cat) =>
      (super.noSuchMethod(
            Invocation.method(#upsertCat, [cat]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
